name: get
on:
  schedule:
    - cron: "0,30 * * * *"

jobs:
  run:
    name: get
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: deps
        run: |
          sudo apt update && sudo apt install -y curl sqlite3

      - uses: robinraju/release-downloader@v1.9
        with:
          repository: ${{ github.repository }}
          tag: "latest"
          fileName: "db.sqlite3"
      
      - name: fetch
        run: |
          curl "https://xml.e-hentai.org/ehg.xml" -o raw

      - name: process
        run: |
          cat raw | grep -P -o "https?://e[-x]hentai.org/g/(\d+)/(\w+)/" | cut -d "/" -f 5,6 | sort -n | uniq | tee data
          printf "INSERT OR IGNORE INTO gallery values" >> insert.sql
          cat data | sed -E 's/(.*)\/(.*)/(\1,"\2"),/' >> insert.sql
          tail -n 1 data | sed -E 's/(.*)\/(.*)/(\1,"\2");/' >> insert.sql
          before=`sqlite3 db.sqlite3 < count.sql`
          sqlite3 db.sqlite3 < insert.sql
          after=`sqlite3 db.sqlite3 < count.sql`
          messages="auto-commit: $((after-before)) new galleries added at `date`"
          echo "messages=$messages"
          echo "messages=$messages" >> $GITHUB_ENV
          diff -N data.txt data || true
          mv data data.txt

      - name: dump sql
        run: |
          sqlite3 db.sqlite3 .dump > dump.sql
      
      - name: prepare release message
        run: |
          count=`sqlite3 db.sqlite3 < count.sql`
          echo \# `date +%Y-%m-%d` >> body.txt
          echo >> body.txt
          echo $count records in total. >> body.txt
          cat body.txt

      - name: upload sql
        uses: actions/upload-artifact@v4
        with:
          name: dump.sql
          path: dump.sql

      - name: upload db
        uses: actions/upload-artifact@v4
        with:
          name: db.sqlite3
          path: db.sqlite3

      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "${{ env.messages }}"
          add: '["data.txt"]'

      - name: update latest tag
        uses: EndBug/latest-tag@latest

      - name: release db to latest
        uses: softprops/action-gh-release@v1
        with:
          body_path: body.txt
          tag_name: "latest"
          target_commitish: main
          files: |
            db.sqlite3

      - name: compute db file name and tag of month
        run: |
          echo "month=v`date '+%Y.%m'`" >> $GITHUB_ENV
          echo "today_db=db-`date '+%Y-%m-%d'`.sqlite3" >> $GITHUB_ENV
          today_db="db-`date '+%Y-%m-%d'`.sqlite3"
          echo $today_db
          mv db.sqlite3 $today_db
          ls -l

      - name: update month tag
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ env.month }}

      - name: release db to month
        uses: softprops/action-gh-release@v1
        with:
          body_path: body.txt
          tag_name: "${{ env.month }}"
          target_commitish: main
          files: |
            ${{ env.today_db }}
